name: "Main"

on:
  release:
    types: [published]
  push:
    branches:
      - "main"

env:
  CLUSTER:  ${{ github.ref != 'refs/remotes/origin/main' && 'assessments-ecs-staging' || 'assessments-ecs-prod' }}

jobs:
  teste:
    runs-on: ubuntu-latest
    steps:
    - name: Get short SHA
      id: slug
      run: echo "::set-output name=sha7::$(echo ${GITHUB_SHA} | cut -c1-7)"
    - name: Set env to deploy
      id: vars
      run: echo "The selected cluster is ${{ env.CLUSTER }} and version id ${{ steps.slug.outputs.sha7 }}"
    - name: Echo ref
      run: echo "${{ github.ref }}"
    - name: Echo release
      run: echo "${{ github.event.release.prerelease }}"
      
      
        
