name: "Main"

on:
  push:
    branches:
      - "main"

env:
  CLUSTER: ${{ format(github.ref != 'refs/heads/main') }}

jobs:
  teste:
    runs-on: ubuntu-latest
    steps:
      - name: Set env to deploy
        id: vars
        run: echo "The selected cluster is ${{ env.CLUSTER }}"
        
