name: "Main"

on:
  push:
    branches:
      - "main"

jobs:
  teste:
    runs-on: ubuntu-latest
    steps:
      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Check outputs
        run: echo ${{ steps.vars.outputs.sha_short }}
      - name: Check outputs
        run: echo ${ GITHUB_SHA:8 }
